### ISSUE TITLE
Unsupported platfrom Windows:amd64

### ISSUE THREAD

**Issue by wwb413** [software-mansion/starknet-jvm#248]
### What happened

Felt publicKey = new StarkCurveSigner(privateKey).getPublicKey();

### Stack trace

Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.swmansion.starknet.signer.StarkCurveSigner$publicKey$2.invoke(StarkCurveSigner.kt:16)
	at com.swmansion.starknet.signer.StarkCurveSigner$publicKey$2.invoke(StarkCurveSigner.kt:16)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.swmansion.starknet.signer.StarkCurveSigner.getPublicKey(StarkCurveSigner.kt:16)
	at com.starnet.util.OpUtils.generateStarkWallet(OpUtils.java:229)
	at com.starnet.util.OpUtils.main(OpUtils.java:244)
Caused by: com.swmansion.starknet.crypto.NativeLoader$UnsupportedPlatform: Unsupported platfrom Windows:amd64
	at com.swmansion.starknet.crypto.NativeLoader.getLibPath(NativeLoader.kt:64)
	at com.swmansion.starknet.crypto.NativeLoader.load(NativeLoader.kt:32)
	at com.swmansion.starknet.crypto.NativeLoader.load(NativeLoader.kt:23)
	at com.swmansion.starknet.crypto.StarknetCurve.<clinit>(StarknetCurve.kt:47)

### Steps to reproduce

1.         Felt privateKey = Felt.fromHex("0x5d4b6d215ca5778e97849fb19e0396806fbc87d4922d8b2322abf670b449c5f");

        Felt publicKey = new StarkCurveSigner(privateKey).getPublicKey();

### SDK Version

0.5.1

### Language

Java

### Language

n/a

### Language version

11

### What operating system are you using?

Windows

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by THenry14** [comment]
Hello @wwb413 , sadly at the moment we do not support windows, and there are no concrete plans to do so in the nearest future. Sorry for inconvenience caused.

**Comment by wwb413** [comment]
Okay, no problem, I switched to Linux instead.
