### ISSUE TITLE
`TypedData#getMessageHash` throws an error for specific request

### ISSUE THREAD

**Issue by kamilargent** [software-mansion/starknet-jvm#251]
### What happened

The SDK throws an error when trying to get a message hash for specific typed data using `TypedData#getMessageHash`.  It looks like parsing of the `Felt` primitive doesn't support `Felt` in the form of `BigInt`. 

This signature request is a production use case from `MintSquare` dapp (signature is requested when trying to modify profile). The same request works fine with `starknet.js`.

### Stack trace

```
java.lang.IllegalArgumentException: Short string cannot be longer than 31 characters.
    at com.swmansion.starknet.data.types.Felt$Companion.fromShortString(Felt.kt:91)
    at com.swmansion.starknet.data.TypedData.valueFromPrimitive(TypedData.kt:83)
    at com.swmansion.starknet.data.TypedData.encodeValue(TypedData.kt:112)
    at com.swmansion.starknet.data.TypedData.encodeData(TypedData.kt:122)
    at com.swmansion.starknet.data.TypedData.getStructHash(TypedData.kt:134)
    at com.swmansion.starknet.data.TypedData.getMessageHash(TypedData.kt:154)
```

### Steps to reproduce

1. Define typed data string using this data:
```json
{
  "domain": { "name": "Mint Square", "chainId": "SN_GOERLI", "version": "2" },
  "message": { "message": "197281386184070998625691365582659491265" },
  "primaryType": "Message",
  "types": {
    "StarkNetDomain": [
      { "name": "name", "type": "felt" },
      { "name": "chainId", "type": "felt" },
      { "name": "version", "type": "felt" }
    ],
    "Message": [{ "name": "message", "type": "felt" }]
  }
}
```
2. Call`TypedData#fromJsonString`
3. Call `TypedData#getMessageHash`

### SDK Version

0.5.2

### Language

Kotlin

### Language

n/a

### Language version

1.7.21

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by kamilargent** [comment]
Another parsing issue example:
## Typed data
```json
{
  "domain": {
    "name": "Mint Square",
    "chainId": "SN_GOERLI",
    "version": "2"
  },
  "message": {
    "isOrderAsk": "0",
    "signer": "0x028c0bee8f761212b631106a05553d94c19316eb72e2d9b258d6890e8cd06b39",
    "collection": "0x03090623ea32d932ca1236595076b00702e7d860696faf300ca9eb13bfe0a78c",
    "price": "100000000000000",
    "tokenId.low": "28081",
    "tokenId.high": "0",
    "amount": "1",
    "strategy": "0x000f9a59ce0dcaed50f7fd7f15aa38793cfc1e1232ca7d341919b486c54b5f43",
    "currency": "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
    "nonce": 0,
    "startTime": "0",
    "endTime": "1712939604",
    "minPercentageToAsk": "8500",
    "params": ""
  },
  "primaryType": "Message",
  "types": {
    "StarkNetDomain": [
      { "name": "name", "type": "felt" },
      { "name": "chainId", "type": "felt" },
      { "name": "version", "type": "felt" }
    ],
    "Message": [
      { "name": "isOrderAsk", "type": "felt" },
      { "name": "signer", "type": "felt" },
      { "name": "collection", "type": "felt" },
      { "name": "price", "type": "felt" },
      { "name": "tokenId.low", "type": "felt" },
      { "name": "tokenId.high", "type": "felt" },
      { "name": "amount", "type": "felt" },
      { "name": "strategy", "type": "felt" },
      { "name": "currency", "type": "felt" },
      { "name": "nonce", "type": "felt" },
      { "name": "startTime", "type": "felt" },
      { "name": "endTime", "type": "felt" },
      { "name": "minPercentageToAsk", "type": "felt" },
      { "name": "params", "type": "felt" }
    ]
  }
}
```

## Stack trace

```
java.lang.NumberFormatException: Zero length BigInteger
	at java.math.BigInteger.<init>(BigInteger.java:485)
	at com.swmansion.starknet.data.ParseHex.parseHex(ParseHex.kt:12)
	at com.swmansion.starknet.data.types.Felt$Companion.fromHex(Felt.kt:80)
	at com.swmansion.starknet.data.types.Felt$Companion.fromShortString(Felt.kt:101)
	at com.swmansion.starknet.data.TypedData.valueFromPrimitive(TypedData.kt:83)
	at com.swmansion.starknet.data.TypedData.encodeValue(TypedData.kt:112)
	at com.swmansion.starknet.data.TypedData.encodeData(TypedData.kt:122)
	at com.swmansion.starknet.data.TypedData.getStructHash(TypedData.kt:134)
	at com.swmansion.starknet.data.TypedData.getMessageHash(TypedData.kt:154)
```
