### ISSUE TITLE
Unable to load poseidon from jar

### ISSUE THREAD

**Issue by DelevoXDG** [software-mansion/starknet-jvm#336]
### Bug 

On Android (from aar) or host machine (from path), `libposeidon_jni` loads fine. When loading from jar, however, the load fails. It seems like jvm can't open the jni. There might be a problem with the way it's built, copied, or uploaded.
This causes failures in Cairo 1 class hash calculations, therefore making declaring, estimating fees for Cairo 1 contracts impossible.

Below is the stack trace from trying to declare cairo 1 contract:  
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/z3/j6qq2t4n0tn0ycjgt4ssnz740000gn/T/poseidon_jni-dir249220908989910654/poseidon_jni: dlopen(/private/var/folders/z3/j6qq2t4n0tn0ycjgt4ssnz740000gn/T/poseidon_jni-dir249220908989910654/poseidon_jni, 0x0001): Library not loaded: @rpath/libposeidon.dylib
  Referenced from: <4B145DD8-F6DC-37D3-8717-11400F15B428> /private/var/folders/z3/j6qq2t4n0tn0ycjgt4ssnz740000gn/T/poseidon_jni-dir249220908989910654/poseidon_jni
  Reason: tried: '/Users/runner/work/starknet-jvm/starknet-jvm/crypto/poseidon/build/poseidon/libposeidon.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/starknet-jvm/starknet-jvm/crypto/poseidon/build/poseidon/libposeidon.dylib' (no such file), '/Users/runner/work/starknet-jvm/starknet-jvm/crypto/poseidon/build/poseidon/libposeidon.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/runner/work/starknet-jvm/starknet-jvm/crypto/poseidon/build/poseidon/libposeidon.dylib' (no such file), '/Applications/IntelliJ IDEA.app/Contents/jbr/Cont
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.swmansion.starknet.crypto.NativeLoader.loadFromJar(NativeLoader.kt:50)
	at com.swmansion.starknet.crypto.NativeLoader.load(NativeLoader.kt:38)
	at com.swmansion.starknet.crypto.NativeLoader.load(NativeLoader.kt:23)
	at com.swmansion.starknet.crypto.Poseidon.<clinit>(Poseidon.kt:72)
	at com.swmansion.starknet.data.Cairo1ClassHashCalculator.computeSierraClassHash(Cairo1ClassHashCalculator.kt:14)
	at com.swmansion.starknet.data.types.transactions.TransactionFactory.makeDeclareV2Transaction(Transaction.kt:504)
	at com.swmansion.starknet.data.types.transactions.TransactionFactory.makeDeclareV2Transaction$default(Transaction.kt:494)
	at com.swmansion.starknet.account.StandardAccount.signDeclare(StandardAccount.kt:125)
	at com.example.javademo.Main.declareCairo1Contract(Main.java:123)
	at com.example.javademo.Main.main(Main.java:85)
```

**Comment by DelevoXDG** [comment]
For now, was able to find some minor difference in obj-dumps:
[local_jni_dump.txt](https://github.com/software-mansion/starknet-jvm/files/13206627/local_jni_dump.txt)
[release_jni_dump.txt](https://github.com/software-mansion/starknet-jvm/files/13206628/release_jni_dump.txt)

1. The numbering of steps is slightly different, but i think it shouldn't be a problem
2. Instruction differences:
  Release: `3a98: 1f 20 03 d5 nop"` 
  Local: `3a88: 08 00 00 b0 adrp x8, 1 ; 0x4000`
  Release: `3dc4: 81 0f 00 10 adr x1, #496 ; literal pool for: "[J" 3dc8: 1f 20 03 d5 nop`
  Local: `3db4: 01 00 00 90 adrp x1, 0 ; 0x3000 3db8: 21 90 3e 91 add x1, x1, #4004 ; literal pool for: "[J"`
3. Local: array, release: address 
  Release: `3a9c: 68 2b 00 58 ldr x8, #1388 ; literal pool symbol address: ___stack_chk_guard` 
  Local: `3a8c: 08 05 40 f9 ldr x8, [x8, #8] ; literal pool symbol address: ___stack_chk_guard`
