### ISSUE TITLE
`StandardAccountTest` fails to init

### ISSUE THREAD

**Issue by franciszekjob** [software-mansion/starknet-jvm#505]
### What happened

Sometimes `StandardAccountTest` fails to init due to below error. This happens irregularly, reruning CI solves the issue.
[Link](https://github.com/franciszekjob/test-speculos-worlkflow/actions/runs/10164572303/job/28110271438) to example of failed CI.

### Stack trace

```
StandardAccountTest > initializationError FAILED
    starknet.utils.data.SnCastCommandFailed: Command declare failed. Error reason: thread 'main' panicked at crates/sncast/src/main.rs:201:14:
    Failed to build contract: Error while compiling Sierra. Make sure you have the latest universal-sierra-compiler binary installed. Contact us if it doesn't help

    Caused by:
        Command universal-sierra-compiler failed with status exit status: 2
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
        at app//starknet.utils.DevnetClient.requireNoErrors(DevnetClient.kt:395)
        at app//starknet.utils.DevnetClient.runSnCast(DevnetClient.kt:382)
        at app//starknet.utils.DevnetClient.declareContract(DevnetClient.kt:253)
        at app//starknet.utils.DevnetClient.declareDeployContract(DevnetClient.kt:315)
        at app//starknet.utils.DevnetClient.declareDeployContract$default(DevnetClient.kt:306)
        at app//starknet.account.StandardAccountTest$Companion.before(StandardAccountTest.kt:60)
        at app//starknet.account.StandardAccountTest.before(StandardAccountTest.kt)

Gradle Test Executor 1 finished executing tests.
```

### Steps to reproduce

n/a

### SDK Version

0.12.2

### Language

Other

### Language

n/a

### Language version

n/a

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

**Comment by franciszekjob** [comment]
The error message `Error while compiling Sierra. Make sure you have the latest universal-sierra-compiler binary installed. Contact us if it doesn't help` is not really descriptive, under the hood USC also fails because of EOF error which occurs in [this line](https://github.com/software-mansion/universal-sierra-compiler/blob/fd6cab4c9887b625660f7c48a137b885451e6349/src/main.rs#L35)

So ultimately this error occurring in this issue seems the same as in https://github.com/software-mansion/starknet-jvm/issues/472.
